# Site settings
title: 
header-img: img/home-bg.png
email: e.nicholl.liepe@gmail.com
copyright_name: e46and2
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  e46and2
learn_profile: e46and2
email_username: e.nicholl.liepe@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
